# Generated by Django 4.2.4 on 2023-08-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='care_provider',
            name='department',
            field=models.CharField(default='Family Medicine', max_length=50),
        ),
    ]
