# Generated by Django 4.2.4 on 2023-08-17 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_care_provider_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='care_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.care_provider'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='purpose',
            field=models.TextField(default='Check up', max_length=250),
        ),
        migrations.AddField(
            model_name='prescription',
            name='date_issued',
            field=models.DateField(default=datetime.date.today, verbose_name='Prescription Date'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(default='Please refer to the instructions provided by your doctor or pharmacist.', max_length=250),
        ),
        migrations.AlterField(
            model_name='care_provider',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
