# Generated by Django 4.2.4 on 2023-08-17 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_appointment_care_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='care_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.care_provider'),
        ),
    ]
